### ISSUE TITLE
text pieces defaults to dark theme

### ISSUE THREAD

**Issue by www-cat** [liferooter/textpieces#104] opened 2022-10-19 20:23 UTC
to reproduce:
1. change settings: `gsettings set org.gnome.desktop.interface color-scheme prefer-light`
2. install text pieces
3. start text pieces

expected:
text pieces is light

actual behavior:
text pieces is dark

**Comment by liferooter** [comment] 2022-10-20 05:46
Duplicate of #92

**Closed by liferooter** 2022-10-20 05:46 UTC
